service: client-service

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}

  logRetentionInDays: 7
  tracing:
    apiGateway: true
    lambda: true

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt:
          - ClientTable
          - Arn

package:
  individually: true

functions:
  create-client:
    package:
      artifact: 'target/client-service.zip'
    handler: 'com.drissamri.client.LambdaHandler::handleRequest'
    runtime: java11
    memorySize: 3008
    timeout: 10
    events:
      - http:
          path: /clients
          method: POST

    environment:
      REGION: ${self:provider.region}
      CLIENT_TABLE: !Ref ClientTable


resources:
  Resources:
    ClientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST